insert into Membro_band (profilo, nome, cognome, nomedarte) values (1, null, null, 'maecenas');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (2, null, null, 'molestie');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (3, null, null, 'nibh');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (4, null, null, 'vulputate luctus');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (5, null, null, 'adipiscing lorem');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (6, null, null, 'dis');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (7, null, null, 'fermentum');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (8, null, null, 'nam dui');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (9, null, null, 'bibendum imperdiet');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (null, 'Jo-ann', 'Atley', 'bibendum morbi');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (11, null, null, 'vulputate vitae');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (null, 'Candra', 'Davers', 'turpis');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (13, null, null, 'nisi volutpat');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (14, null, null, 'pellentesque volutpat');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (15, null, null, 'cras in');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (16, null, null, 'fringilla');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (17, null, null, 'iaculis');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (18, null, null, 'augue vel');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (19, null, null, 'vestibulum');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (20, null, null, 'lacinia');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (21, null, null, 'quam');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (22, null, null, 'congue');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (null, 'Barnebas', 'Heddon', 'vel nisl');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (null, 'Melissa', 'Mont', 'amet');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (25, null, null, 'habitasse platea');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (null, 'Virge', 'Gascard', 'mollis molestie');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (27, null, null, 'ipsum');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (28, null, null, 'enim lorem');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (29, null, null, 'ut');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (30, null, null, 'egestas');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (31, null, null, 'cras');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (32, null, null, 'etiam faucibus');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (33, null, null, 'interdum venenatis');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (34, null, null, 'sem fusce');
insert into Membro_band (profilo, nome, cognome, nomedarte) values (35, null, null, 'ligula');
