insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('sit amet', '[221,897]', 71, 22);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('rutrum', '[57,183]', 72, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('ipsum', '[63,887]', 73, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('cum sociis', '[61,166]', 74, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('convallis tortor', '[28,956]', 75, 17);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('nisi', '[34,120]', 76, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('est', '[6,126]', 77, 79);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('tortor quis', '[17,154]', 78, 109);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('in hac', '[6,143]', 79, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('sociis', '[5,168]', null, 97);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('nunc proin', '[476,994]', 81, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('sit amet', '[23,104]', 82, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('vestibulum', null, 83, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('suscipit', '[129,954]', 84, 98);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('justo maecenas', '[28,140]', 85, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('nec condimentum', '[123,754]', null, 13);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('ipsum primis', '[76,153]', 87, null);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('blandit non', '[72,107]', 88, 74);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('ut', '[409,525]', 89, 82);
insert into Profilo_band (nome_band, range_prezzo, foto_profilo, id_sede) values ('eu', '[35,138]', 90, 105);
